name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install pre-commit
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit

    - name: Run pre-commit checks
      run: pre-commit run --all-files

    - name: Test fork.sh script
      run: |
        # Test basic usage (script will do its own validation)
        ./fork.sh test-agent
        ./fork.sh test-agent-named TestAgent

        # Verify directories were created in test-agent
        test -d test-agent/journal
        test -d test-agent/tasks/{active,done,new,paused,cancelled}
